<?php
/**
 * Custom Drupal module for the ILGA Membership approval process
 *
 * @author Klaas Eikelboom (CiviCooP)
 * @date 25 juni 2018
 * @license AGPL-3.0
 */

const ILGA_SCHOLARSHIP_APPLICATION_WEBFORM_NID = 'ilga_scholarship_application_webform_id';
const ILGA_SCHOLARSHIP_EVALUATION_WEBFORM_NID = 'ilga_scholarship_evaluation_webform_id';
const ILGA_SCHOLARSHIP_DISABILITY_CUSTOM_FIELD = 'ilga_scholarship_disability_custom_field';
const ILGA_SCHOLARSHIP_SEXUAL_IDENTITY_CUSTOM_FIELD = 'ilga_scholarship_sexual_identity_custom_field';
const ILGA_SCHOLARSHIP_SEXUAL_IDENTITY_OPTION_GROUP = 'ilga_scholarship_sexual_identity_option_group';

const ILGA_SCHOLARSHIP_GENDER_IDENTITY_CUSTOM_FIELD = 'ilga_scholarship_gender_identity_custom_field';
const ILGA_SCHOLARSHIP_GENDER_IDENTITY_OPTION_GROUP = 'ilga_scholarship_gender_identity_option_group';

const ILGA_SCHOLARSHIP_INTERSEX_CUSTOM_FIELD = 'ilga_scholarship_intersex_custom_field';
const ILGA_SCHOLARSHIP_INDIGENOUS_CUSTOM_FIELD = 'ilga_scholarship_indigenous_custom_field';
const ILGA_SCHOLARSHIP_MARGINALISED_CUSTOM_FIELD = 'ilga_scholarship_marginalised_custom_field';
const ILGA_SCHOLARSHIP_HIV_CUSTOM_FIELD = 'ilga_scholarship_hiv_custom_field';
const ILGA_SCHOLARSHIP_SEXWORKER_CUSTOM_FIELD = 'ilga_scholarship_sexworker_custom_field';

const ILGA_SCHOLARSHIP_RECEIVED_CUSTOM_FIELD = 'ilga_scholarship_received_custom_field';
const ILGA_SCHOLARSHIP_WORKSHOP_CUSTOM_FIELD = 'ilga_scholarship_workshop_custom_field';
const ILGA_SCHOLARSHIP_SCORE_CUSTOM_FIELD = 'ilga_scholarship_score_custom_field';
const ILGA_SCHOLARSHIP_EVALUATION_CUSTOM_FIELD = 'ilga_scholarship_evaluation_custom_field';
const ILGA_SCHOLARSHIP_EVALUATION_TOTAL_CUSTOM_FIELD = 'ilga_scholarship_evaluation_total_custom_field';
const ILGA_SCHOLARSHIP_SCORE_EXPLANATION_CUSTOM_FIELD = 'ilga_scholarship_score_explanation_custom_field';
const ILGA_SCHOLARSHIP_CASE_TYPE = 'ilga_scholarship_case_type';
const ILGA_SCHOLARSHIP_EVALUATE_ACTIVITY_TYPE = 'ilga_scholarship_evaluate_activity_type';
const ILGA_SCHOLARSHIP_REFERENCE_DATE = 'ilga_scholarship_reference_date';

// stuff for membership

const ILGA_SCHOLARSHIP_REPRESENTING_RELATION_TYPE = 'ilga_scholarship_representing_relation_type';
const ILGA_SCHOLARSHIP_VALID_MEMBERSHIP_TYPES = 'ilga_scholarship_valid_membership_types';


/**
 * Drupal menu hook
 * @return array
 */
function ilga_scholarship_menu(){
  $items = [];
  $items['admin/config/system/ilga-scholarship'] = [
    'title' => 'ILGA Scholarship configuration',
    'description' => 'Configure the scholarship applicants module',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['_ilga_scholarship_config_form'],
    'access arguments' => ['access administration pages'],
    'type' => MENU_NORMAL_ITEM,
  ];
  return $items;
}

/**
 * Configuration form
 *
 * @param $form
 * @param $form_state
 *
 * @return mixed
 * @throws \CiviCRM_API3_Exception
 */
function _ilga_scholarship_config_form($form, &$form_state){
  civicrm_initialize();
  $webformOptions = _ilga_scholarship_webformOptions();
  $scholarShipApplicationCustomfields = _ilga_scholarship_customFieldOptions('Scholarship_application');
  $evaluationCustomfields = _ilga_scholarship_customFieldOptions('Evaluation');
  $caseTypes = _ilga_scholarship_caseTypes();
  $activityTypes = _ilga_scholarship_activityTypes();
  $relationshipTypes = _ilga_scholarship_relationshipTypes();
  $optionGroups = _ilga_scholarship_optionGroups();

  $form['webforms'] = [
    ILGA_SCHOLARSHIP_APPLICATION_WEBFORM_NID => [
      "#title" => 'Select the webform that is used for the scholarship application',
      '#type' => 'select',
      '#options' => $webformOptions,
      '#default_value' => variable_get(ILGA_SCHOLARSHIP_APPLICATION_WEBFORM_NID, array_keys($webformOptions)[0]),
    ],
    ILGA_SCHOLARSHIP_EVALUATION_WEBFORM_NID => [
      "#title" => 'Select the webform that is used for the scholarship evaluation activity',
      '#type' => 'select',
      '#options' => $webformOptions,
      '#default_value' => variable_get(ILGA_SCHOLARSHIP_EVALUATION_WEBFORM_NID, array_keys($webformOptions)[0]),
    ],
    '#type' => 'fieldset',
    '#title' => 'Forms Configuration',
  ];

  $form[ILGA_SCHOLARSHIP_SEXUAL_IDENTITY_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for sexual identity',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_SEXUAL_IDENTITY_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];
  $form[ILGA_SCHOLARSHIP_SEXUAL_IDENTITY_OPTION_GROUP] = [
    "#title" => 'Option Group that selects the values of the sexual identity',
    '#type' => 'select',
    '#options' => $optionGroups,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_SEXUAL_IDENTITY_OPTION_GROUP, array_keys($optionGroups)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_GENDER_IDENTITY_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for gender identity',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_GENDER_IDENTITY_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_GENDER_IDENTITY_OPTION_GROUP] = [
    "#title" => 'Option Group that selects the values of the gender identity',
    '#type' => 'select',
    '#options' => $optionGroups,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_GENDER_IDENTITY_OPTION_GROUP, array_keys($optionGroups)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_INTERSEX_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for intersex',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_INTERSEX_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_INDIGENOUS_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for indigenous or traditional group',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_INDIGENOUS_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_MARGINALISED_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for a marginalised group',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_MARGINALISED_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_HIV_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for a person living with hiv',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_HIV_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_SEXWORKER_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for a sex worker',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_SEXWORKER_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_DISABILITY_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for disability',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_DISABILITY_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_RECEIVED_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field received previsions scholarship',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_RECEIVED_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_WORKSHOP_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for applying for workshop proposal',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_WORKSHOP_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_SCORE_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for recording the score',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_SCORE_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_SCORE_EXPLANATION_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for recording the score motivation',
    '#type' => 'select',
    '#options' => $scholarShipApplicationCustomfields,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_SCORE_EXPLANATION_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_CASE_TYPE] = [
    "#title" => 'Type of the scholar application case',
    '#type' => 'select',
    '#options' => $caseTypes,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_CASE_TYPE, array_keys($caseTypes)[0]),
  ];

  $form['membership'] = [
    '#type' => 'fieldset',
    '#title' => 'Membership',
    ILGA_SCHOLARSHIP_REPRESENTING_RELATION_TYPE => [
      '#title' => 'Representing Relation ship',
      '#type' => 'select',
      '#options' => $relationshipTypes,
      '#default_value' => variable_get(ILGA_SCHOLARSHIP_EVALUATE_ACTIVITY_TYPE, array_keys($relationshipTypes)[0]),
    ],
    ILGA_SCHOLARSHIP_VALID_MEMBERSHIP_TYPES => [
      '#title' => 'Valid membership types',
      '#type'  => 'checkboxes',
      '#options' => _ilga_scholarship_membershipTypes(),
      '#default_value' => variable_get(ILGA_SCHOLARSHIP_VALID_MEMBERSHIP_TYPES,[]),
    ]
  ];

  $form['evaluation'] = [
    '#type' => 'fieldset',
    '#title' => 'Scholarship Evaluation',
    ILGA_SCHOLARSHIP_EVALUATE_ACTIVITY_TYPE => [
      "#title" => 'Activity type of the scholarship application',
      '#type' => 'select',
      '#options' => $activityTypes,
      '#default_value' => variable_get(ILGA_SCHOLARSHIP_EVALUATE_ACTIVITY_TYPE, array_keys($activityTypes)[0]),
    ],
    ILGA_SCHOLARSHIP_EVALUATION_CUSTOM_FIELD => [
      "#title" => 'Score field for the evaluator',
      '#type' => 'select',
      '#options' => $evaluationCustomfields,
      '#default_value' => variable_get(ILGA_SCHOLARSHIP_EVALUATION_CUSTOM_FIELD, array_keys($evaluationCustomfields)[0]),
    ],
    ILGA_SCHOLARSHIP_EVALUATION_TOTAL_CUSTOM_FIELD => [
      "#title" => 'Total score of the evaluation on the case',
      '#type' => 'select',
      '#options' => $scholarShipApplicationCustomfields,
      '#default_value' => variable_get(ILGA_SCHOLARSHIP_EVALUATION_TOTAL_CUSTOM_FIELD, array_keys($scholarShipApplicationCustomfields)[0]),
    ],
  ];

  $form[ILGA_SCHOLARSHIP_REFERENCE_DATE] = [
    "#title" => 'Reference date for calculating age',
    '#type' => 'date',
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_REFERENCE_DATE),
  ];

  return system_settings_form($form);
}

/**
 * @return array
 * @throws \CiviCRM_API3_Exception
 */
function _ilga_scholarship_activityTypes() {
  $result = civicrm_api3('OptionValue', 'get', [
    'return' => ['value','name'],
    'option_group_id' => "activity_type",
    'options' => ['limit' => 0, 'sort' => 'name'],
  ]);

  $activityTypes = [];
  foreach ($result['values'] as $value) {
    $activityTypes[$value['value']] = $value['name'];
  }
  return $activityTypes;
}

/**
 * @return array
 * @throws \CiviCRM_API3_Exception
 */
function _ilga_scholarship_caseTypes() {
  $caseTypes = [];
  $result = $result = civicrm_api3('CaseType', 'get', [
    'return' => ["title"],
  ]);
  foreach($result['values'] as $value){
    $caseTypes[$value['id']] = $value['title'];
  }
  return $caseTypes;
}

function _ilga_scholarship_relationshipTypes(){
  $relationshipTypes = [];
  $result = $result = civicrm_api3('RelationshipType', 'get', [
    'return' => ['name_a_b'],
    'options' => ['limit' =>0,'sort'=>'name_a_b']
  ]);
  foreach($result['values'] as $value){
    $relationshipTypes[$value['id']] = $value['name_a_b'];
  }
  return $relationshipTypes;
}

function _ilga_scholarship_membershipTypes(){
  $membershipTypes = [];
  $result = $result = civicrm_api3('MembershipType', 'get', [
    'return' => ['name'],
    'options' => ['limit' =>0,'sort'=>'name']
  ]);
  foreach($result['values'] as $value){
    $membershipTypes[$value['id']] = $value['name'];
  }
  return $membershipTypes;
}

/**
 * @return array
 * @throws \CiviCRM_API3_Exception
 */
function _ilga_scholarship_customFieldOptions($customGroup) {
  $customFieldOptions = [];
  try {
    $result = civicrm_api3('CustomField', 'get', [
      'sequential' => 1,
      'return' => ['label'],
      'custom_group_id' => $customGroup,
      'options' => [
        'limit' => 0,
        'sort'  => 'label'
      ]
    ]);
    foreach ($result['values'] as $value) {
      $customFieldOptions['custom_' . $value['id']] = $value['label'];
    }
  } catch (CiviCRM_API3_Exception $ex) {
    throw new Exception('Unable to load customgroup '.$customGroup);
  }

  return $customFieldOptions;
}

/**
 * @return array
 * @throws \CiviCRM_API3_Exception
 */
function _ilga_scholarship_optionGroups() {
  $optionGroups = [];
  $result = civicrm_api3('OptionGroup', 'get', array(
    'return' => ['name','title'],
    'options' => ['limit' => 0 , 'sort' => 'title'],
    'is_active' => 1,
  ));
  foreach ($result['values'] as $value) {
    $optionGroups[$value['name']] = $value['title'];
  }
  return $optionGroups;
}

/**
 * @return array all the published and unpublished webforms
 */
function _ilga_scholarship_webformOptions() {
  $query = db_query("SELECT nid, title FROM {node} WHERE type='webform'");
  $webformOptions = [];
  $records = $query->fetchAll();
  foreach ($records as $record) {
    $webformOptions[$record->nid] = $record->title;
  }
  return $webformOptions;
}

/**
 * Calculate the scholarship score after updating the webform
 *
 * @param $node
 * @param $submission
 */
function ilga_scholarship_webform_submission_update($node, $submission) {
  module_load_include('inc', 'webform', 'includes/webform.submissions');
  if($node->nid==variable_get(ILGA_SCHOLARSHIP_APPLICATION_WEBFORM_NID)){
    $cases = $submission->civicrm['case'];
    civicrm_initialize();
    foreach($cases as $case) {
      $scholarship = new CRM_Scholarship_Score($case['id']);
      $scholarship->process();
    }
  } elseif($node->nid==variable_get(ILGA_SCHOLARSHIP_EVALUATION_WEBFORM_NID)){
      $activities = $submission->civicrm['activity'];
      civicrm_initialize();
      foreach($activities as $activity){
        $evaluation = new CRM_Scholarship_Evaluation($activity['id']);
        $evaluation->process();
      }
  }
}

/**
 * Calculate the scholarship score after submitting the webform
 * @param $node
 * @param $submission
 */
function ilga_scholarship_webform_submission_insert($node, $submission) {
  module_load_include('inc', 'webform', 'includes/webform.submissions');
  if ($node->nid == variable_get(ILGA_SCHOLARSHIP_APPLICATION_WEBFORM_NID)) {
    // the submission is assigned a case id by the webforms_civicrm module hook
    // load the submission to have latest data
    $completeSubmission = webform_get_submission($node->nid, $submission->sid);
    $cases = $completeSubmission->civicrm['case'];
    civicrm_initialize();
    foreach ($cases as $case) {
      $scholarship = new CRM_Scholarship_Score($case['id']);
      $scholarship->process();
    }
  }
  elseif ($node->nid == variable_get(ILGA_SCHOLARSHIP_EVALUATION_WEBFORM_NID)) {
    $completeSubmission = webform_get_submission($node->nid, $submission->sid);
    $activities = $completeSubmission->civicrm['activity'];
    civicrm_initialize();
    foreach ($activities as $activity) {
      $evaluation = new CRM_Scholarship_Evaluation($activity['id']);
      $evaluation->process();
    }
  }
}

/**
 * The weight of this module must be larger als webform civicrm to ensure
 * the hooks execute after the webform civicrm hooks
 */
function ilga_scholarship_install() {
  db_update('system')
    ->fields(['weight' => 8])
    ->condition('name', 'ilga_scholarship', '=')
    ->execute();
}

/**
 * Add the custom view elements
 * @return array
 */
function ilga_scholarship_views_api() {
  return [
    'api' => 3.0,
    'path' => drupal_get_path('module', 'ilga_scholarship') . '/includes',
  ];
}

