<?php
/**
 * Custom Drupal module for the ILGA Membership approval process
 *
 * @author Klaas Eikelboom (CiviCooP)
 * @date 05 juli 2017
 * @license AGPL-3.0
 */

const ILGA_SCHOLARSHIP_APPLICATION_WEBFORM_NID = 'ilga_scholarship_application_webform_id';
const ILGA_SCHOLARSHIP_EVALUATION_WEBFORM_NID = 'ilga_scholarship_evaluation_webform_id';
const ILGA_SCHOLARSHIP_DISABILITY_CUSTOM_FIELD = 'ilga_scholarship_disability_custom_field';
const ILGA_SCHOLARSHIP_OPPRESSED_CUSTOM_FIELD = 'ilga_scholarship_oppressed_custom_field';
const ILGA_SCHOLARSHIP_SCORE_CUSTOM_FIELD = 'ilga_scholarship_score_custom_field';
const ILGA_SCHOLARSHIP_SCORE_EXPLANATION_CUSTOM_FIELD = 'ilga_scholarship_score_explanation_custom_field';
const ILGA_SCHOLARSHIP_CASE_TYPE = 'ilga_scholarship_case_type';
const ILGA_SCHOLARSHIP_EVALUATE_ACTIVITY_TYPE = 'ilga_scholarship_evaluate_activity_type';

function ilga_scholarship_menu(){
  $items = [];
  $items['admin/config/system/ilga-scholarship'] = [
    'title' => 'ILGA Scholarship configuration',
    'description' => 'Configure the scholarship applicants module',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['_ilga_scholarship_config_form'],
    'access arguments' => ['access administration pages'],
    'type' => MENU_NORMAL_ITEM,
  ];
  return $items;
}

function _ilga_scholarship_config_form($form, &$form_state){
  $query = db_query("SELECT nid, title FROM {node} WHERE type='webform'");
  $webformOptions = [];
  $records = $query->fetchAll();
  foreach ($records as $record) {
    $webformOptions[$record->nid] = $record->title;
  }

  civicrm_initialize();

  $result = civicrm_api3('CustomField', 'get', array(
    'sequential' => 1,
    'return' => array("label"),
    'custom_group_id' => "Scholarship_application",
  ));

  $customFieldOptions = [];
  foreach($result['values'] as $value){
    $customFieldOptions['custom_'.$value['id']]=$value['label'];
  }

  $result = $result = civicrm_api3('CaseType', 'get', array(
    'return' => array("title"),
  ));

  $caseTypes = [];
  foreach($result['values'] as $value){
    $caseTypes[$value['id']] = $value['title'];
  }


  $result = civicrm_api3('OptionValue', 'get', array(
    'return' => array("name"),
    'option_group_id' => "activity_type",
    'options' => array('limit' => 0),
  ));

  $activityTypes = [];
  foreach($result['values'] as $value){
    $activityTypes[$value['id']] = $value['name'];
  }

  $form[ILGA_SCHOLARSHIP_APPLICATION_WEBFORM_NID] = [
    "#title" => 'Select the webform that is used for the scholarship application',
    '#type' => 'select',
    '#options' => $webformOptions,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_APPLICATION_WEBFORM_NID, array_keys($webformOptions)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_EVALUATION_WEBFORM_NID] = [
    "#title" => 'Select the webform that is used for the scholarship evaluation activity',
    '#type' => 'select',
    '#options' => $webformOptions,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_EVALUATION_WEBFORM_NID, array_keys($webformOptions)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_DISABILITY_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for disability',
    '#type' => 'select',
    '#options' => $customFieldOptions,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_DISABILITY_CUSTOM_FIELD, array_keys($webformOptions)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_OPPRESSED_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for oppressed groups',
    '#type' => 'select',
    '#options' => $customFieldOptions,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_OPPRESSED_CUSTOM_FIELD, array_keys($webformOptions)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_SCORE_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for recording the score',
    '#type' => 'select',
    '#options' => $customFieldOptions,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_SCORE_CUSTOM_FIELD, array_keys($webformOptions)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_SCORE_EXPLANATION_CUSTOM_FIELD] = [
    "#title" => 'Custom Case field for recording the score motivation',
    '#type' => 'select',
    '#options' => $customFieldOptions,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_SCORE_EXPLANATION_CUSTOM_FIELD, array_keys($webformOptions)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_CASE_TYPE] = [
    "#title" => 'Type of the scholar application case',
    '#type' => 'select',
    '#options' => $caseTypes,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_CASE_TYPE, array_keys($webformOptions)[0]),
  ];

  $form[ILGA_SCHOLARSHIP_EVALUATE_ACTIVITY_TYPE] = [
    "#title" => 'Activity type of the scholarship application',
    '#type' => 'select',
    '#options' => $activityTypes,
    '#default_value' => variable_get(ILGA_SCHOLARSHIP_EVALUATE_ACTIVITY_TYPE, array_keys($webformOptions)[0]),
  ];

  return system_settings_form($form);
}

function ilga_scholarship_webform_submission_update($node, $submission) {
  module_load_include('inc', 'webform', 'includes/webform.submissions');
  if($node->nid==variable_get(ILGA_SCHOLARSHIP_APPLICATION_WEBFORM_NID)){
    $cases = $submission->civicrm['case'];
    civicrm_initialize();
    foreach($cases as $case) {
      $scholarship = new ilga_scholarship_score($case['id']);
      $scholarship->process();
    }
  }
}

function ilga_scholarship_webform_submission_insert($node, $submission) {
  module_load_include('inc', 'webform', 'includes/webform.submissions');
  if($node->nid==variable_get(ILGA_SCHOLARSHIP_APPLICATION_WEBFORM_NID)){

    // the submission is assigned a case id by the webforms_civicrm module hook
    // load the submission to have latest data
    $completeSubmission = webform_get_submission($node->nid,$submission->sid);
    $cases = $completeSubmission->civicrm['case'];
    civicrm_initialize();
    foreach($cases as $case) {
      $scholarship = new ilga_scholarship_score($case['id']);
      $scholarship->process();
    }
  }
}

function ilga_scholarship_views_api() {
  return [
    'api' => 3.0,
    'path' => drupal_get_path('module', 'ilga_scholarship') . '/includes',
  ];
}
